version: '3.7'

services:

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: test_app
      MYSQL_USER: test_app
      MYSQL_PASSWORD: app_test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'